### ISSUE TITLE
Option for "clear input on tab"

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#47]
Hi there,

I think it could be a good idea to provide an option to clear an input field, when the user tabs in.

My app, for example, has a input field for adding a zip code. It's prefilled with the zip of the users current location - but he should be able to change it at any time. 

For now, the user has to clear the value by himself or press the "X" if I enabled the "clearable" option. But both steps are one stept to much for a great usability. If the user tabs into the field, we already know that he wants to add a new value, so it should be possible to clear it directly.

**Comment by TheJuki** [comment]
I am trying to think of a way to do this. I do not think there is a way to tell that a field become focused because of Action Next or Tab event. If a user just taps a field with text it, it would also clear the text. Perhaps you just want the entire text in a field to be selected so that when the next character is typed, the previous highlighted text is cleared?

**Comment by TheJuki** [comment]
I just released [4.7.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if clearOnFocus works for you. Check out the docs: https://thejuki.github.io/KFormMaster/element/base/#clear-on-focus

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
