### ISSUE TITLE
Icons for segmented buttons

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#58]
Hi there,

I do have a great suggestion to improve the design of the forms. There should be a possibility to add an icon (drawable) to a segmented button to archive something like this:

![icons](https://user-images.githubusercontent.com/8148815/46292802-16031d00-c592-11e8-9cfc-97bf36495800.png)

**Comment by TheJuki** [comment]
See https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/FullscreenFormActivity.kt#L444

What I came up with is an interface with one property: drawable.

Your object would implement the SegmentedDrawable interface and override drawable so that each object could use a different drawable.

See https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/item/SegmentedListItem.kt

Also, since it is possible for the drawable to set to the left, right, top or bottom, I added a property to the form element: drawableDirection which used the new enum class: FormSegmentedElement.DrawableDirection.

What do you think of this solution?

**Comment by darkwood-studios** [comment]
@TheJuki 
Yeah, that should work great.

**Comment by TheJuki** [comment]
I just released [5.0.2](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency. I added the ability to set the [drawableRes](https://thejuki.github.io/KFormMaster/element/segmented/#drawable-direction) for each item in the Segmented element group.

**Comment by darkwood-studios** [comment]
Works perfect. Thanks for great work.
